# **2.0 - Algebra Linear**
---

## **Vetores**: 

Vetores podem ser entendidos como pontos no espaço e podemos representar os dados usando vetores. Exemplo: os dados que representam um apartamento, as notas de um aluno, os valores que compõem o preço de um produto, entre outros, podem ser armazenados em um vetor.

No Python representamos um vetor como um array do NumPy, então se temos apenas a informação da quantidade de m², temos um vetor com um eixo:

In [1]:
import numpy as np

apto = np.array([67])

Adicionando a informação do valor do apartamento no vetor, teremos um vetor com dois eixos:

In [2]:
apto = np.array([67, 250])

Se continuarmos incluindo mais uma informação como a quantidade de quartos, teremos vetor três eixos:

In [3]:
apto = np.array([67, 250, 2])

E podemos continuar adicionando informações no vetor e a cada novo valor aumentamos um eixo do vetor.

&emsp; Abaixo é mostrado como um vetor pode ser representado visualmente até o terceiro eixo.

![fig1](http://www.sakurai.dev.br/images/posts/2019-06-21-revisao-algebra-linear-python-01.png)

## **Métodos úteis da np.array**

In [4]:
x = np.array([1, 2, 3, 4])
x.sum() # soma dos valores do vetor = 10
x.min() # menor valor do vetor = 1
x.max() # maior valor do vetor = 4

4

## **Soma de vetores**

Dois ou mais vetores (de tamanho igual) podem ser somados e para isso é calculado a soma de cada elemento nas mesmas posições do vetor, exemplo:

Exemplo: quando temos um vetor com valores de almoço e outro vetor com valores de gorjetas, podemos somar os dois vetores para obter o valor total de cada refeição.

In [5]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
soma = x + y  #[6, 8, 10, 12]

## **Soma escalar**

Também é possível fazer a soma escalar (com um número) no vetor, então um valor é somado a cada elemento do vetor. Exemplo, suponha um conjunto de média de notas dos alunos, e o professor bonzinho resolve dar 0.5 pontos para cada aluno:

In [6]:
notas = np.array([6.5, 8.0, 7.5, 4.5, 9.0, 6.5, 6.0, 5.5, 7.0, 8.0, 6.5, 7.5])
soma = notas + 0.5  #[7.0, 8.5, 8.0, 5.0, 9.5, 7.0, 6.5, 6.0, 7.5, 8.5, 7.0, 8.0]

## **Operações do array no Numpy**

Com o novo vetor de notas, queremos saber quais os alunos obtiveram nota maior ou igual a 7.0 e foram aprovados. Para isso, podemos aplicar uma comparação a cada elemento do vetor, exemplo:

In [7]:
aprovados = soma >= 7.0
# o resultado é um vetor de booleanos: 
# array([True, True, True, False, True, True, False, False, True, True, True, True], dtype=bool) 
# que indica com True as notas que são maior ou igual a 7,0 e False as notas menores que 7,0.

E contar quantos valores são **True**, portanto tem nota maior ou igual a 7.0:

In [10]:
qtdAprovados = sum(soma >= 7.0) 
qtdAprovados

9

O mesmo pode ser feito para saber quantos alunos tiveram a nota menor que 7.0 e foram reprovados. Podemos aplicar uma comparação a cada elemento do vetor, exemplo:

In [11]:
reprovados = soma < 7.0
reprovados

array([False, False, False,  True, False, False,  True,  True, False,
       False, False, False])

E contar quantos valores são **True**, portanto tem nota menor que 7.0:

In [12]:
qtdReprovados = sum(soma < 7.0)
qtdReprovados

3

## **Multiplicação de vetores**

Dois ou mais vetores podem ser multiplicados e para isso é calculado a multiplicação de cada elemento nas mesmas posições do vetor, exemplo:

In [14]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
mult = x * y
mult

array([ 5, 12, 21, 32])

Se temos um vetor com as notas de um aluno:

In [16]:
notas = np.array([8.0, 7.0, 7.5, 9.5, 10.0])

E temos um vetor com o peso que representa cada uma das notas na disciplina:

In [19]:
pesos = np.array([0.2, 0.1, 0.1, 0.3, 0.3])

Se multiplicarmos os dois vetores e somar seus valores, temos como resultado a nota que este aluno teve na disciplina:

In [20]:
notaFinal = sum(notas * pesos)

## **Multiplicação de escalar**

Também é possível fazer a multiplicação escalar (com um número) no vetor, então um valor é multiplicado a cada elemento do vetor. Exemplo, suponha que temos um vetor os valores pagos com comida em um restaurante: 

In [21]:
valores = np.array([18.0, 16.5, 17.0, 19.5, 18.5])

E queremos calcular 10% de gorjetas para cada um dos valores:

In [23]:
gorjeta = valores * .1
gorjeta

array([1.8 , 1.65, 1.7 , 1.95, 1.85])

Se quiser saber o total de gorjeta é só somar o vetor **sum(gorjeta)**

## **Produto interno de vetores**

O produto escalar de dois vetores é dado por: 

$\sum^{n-1}_{i=0} x_i . y_i = x_0 . y_0 + x_1 . y_1+...+x_n.y_n$

sendo **x** e **y**, dois vetores de tamanho iguais e **n** o tamanho dos vetores, o produto escalar é a somatória da multiplicação de dois vetores, exemplo:

In [24]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
prod = np.dot(x, y)
prod

70

Para calcular a soma dos quadrados de um vetor, também podemos usar o produto escalar como mostrado: 

$\sum^{n-1}_{i=0} x^2_i = x^2_0 + x^2_1 + ... + x^2_n$

In [26]:
x = np.array([1, 2, 3, 4])
prod = np.dot(x, x)
prod

30

## **Distância ente vetores**

Na imagem abaixo temos o vetor **[1, 4] (quadrado verde)** e um vetor **[2, 1] (quadrado azul)**. Temos um novo vetor **[4, 2] (triângulo vermelho)**, mas gostaríamos de classificar este novo vetor como quadrado verde ou azul. Para isso podemos verificar qual o quadrado mais próximo e usar a mesma cor, mas qual quadrado está mais perto do triângulo?

![fig_2](http://www.sakurai.dev.br/images/posts/2019-06-21-revisao-algebra-linear-python-04.png)

Podemos pela imagem abaixo perceber que o quadrado azul está mais próximo do triângulo vermelho, entãopodemos classificar este novo vetor como um quadrado azul.

![fig_3](http://www.sakurai.dev.br/images/posts/2019-06-21-revisao-algebra-linear-python-05.png)

Uma das formas de calcular a distância entre vetores é usando a **Distância Euclidiana**, que é dada pela equação: $$\sqrt{\sum^{n-1}_{i=0} (a_i - b_i)^2}$$

Então, na **Figura 7** calculamos a distância euclidiana entre o vetor **[1, 4] (quadrado verde)** com o vetor  **[4, 2] (triângulo vermelho)**.

Distância Euclidiana: $\sqrt{(1 - 4)^2+(4-2)^2} = \sqrt{9+4} = \sqrt{13} = 3.6055$

E na fórmula abaixo calculamos a distância euclidiana entre o vetor **[2, 1] (quadrado azul)** com o vetor **[4, 2] (triângulo vermelho)** $$\sqrt{(2-4)^2+(1-2)^2} = \sqrt{4+1} = \sqrt{5}=2.2360$$

Portanto, sabemos que a menor distância é em relação ao quadrado azul.

Usando Python, podemos calcular a distância entre os vetores:

In [27]:
qv = np.array([1,4])    # Quadrado verde
qa = np.array([2,1])    # Quadrado azul
tv = np.array([4,2])    # Triângulo vermelho

com:

In [28]:
distanciaQuadradoVerde = np.sqrt(sum((qv - tv) ** 2))
distanciaQuadradoAzul  = np.sqrt(sum((qa - tv) ** 2))

print('Distancia Quadrado Verde {}\nDistancia Quadrado Azul {}'.format(distanciaQuadradoVerde, 
                                                                       distanciaQuadradoAzul))

Distancia Quadrado Verde 3.605551275463989
Distancia Quadrado Azul 2.23606797749979


## **Matrizes**

Matriz é formada por um conjunto de vetores, normalmente representada em maíusculo, como **A[m,n]** que tem **m** linhas por **n** colunas. O Numpy tem o objeto **matrix** que representa uma matriz, por exemplo:

In [29]:
A = np.matrix([[1, 2, 3, 4],
               [5, 6, 7, 8]])

Nesse caso dizemos que a matriz **A** tem tamanho **[2,4]**, ou duas linhas e quatro colunas. Para acessar uma determinada posição da matriz precisamos informar os valores da linha e coluna, lembrando que os índices começam com **zero**, o valor da posição **A[1, 3]** é **8**.

## **Soma de matrizes**

A soma de matrizes: 

In [31]:
A = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])
B = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])

SOMA = A + B
SOMA

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16]])

## Transposta

Com o Numpy podemos obter facilmente a transposta de uma matriz:

In [33]:
A = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])
A.T

matrix([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

## Multiplicaçaõ de matrizes

Para multiplicar duas matrizes é necessário que uma matriz **A** tenha dimansão **m x n** equanto que a matriz **B** tenha a dimensão **n x m**, como resultado tomar uma matriz de dimensão **m x n**.

In [34]:
A = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])
B = np.matrix([[1, 2],
               [3, 4], 
               [5, 6],
               [7, 8]])
mult = A * B 
mult

matrix([[ 50,  60],
        [114, 140]])

# Conclusão

<p> Como vemos acima as matrizes são a base fundamental do Numpy, portanto quando precisamos trabalhar com conjuntos de dados é fácil ver que estamos aplicando álgebra em todas as nossas manipulações.